apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: poc-asiayo-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
volumeBindingMode: WaitForFirstConsumer
